### ISSUE TITLE
gem fails to install with 'invalid byte sequence in US-ASCII'

### ISSUE THREAD

**Issue by fintanf** [rvm/rvm-gem#1]
I'm having an issue installing the latest version of the gem (1.11.3.2). Here's the output with backtrace:

<pre>
ubuntu@machine:~$ sudo gem install rvm --backtrace
ERROR:  While executing gem ... (ArgumentError)
    invalid byte sequence in US-ASCII
    /usr/lib/ruby/1.9.1/rubygems/specification.rb:519:in `normalize_yaml_input'
    /usr/lib/ruby/1.9.1/rubygems/specification.rb:479:in `from_yaml'
    /usr/lib/ruby/1.9.1/rubygems/package/tar_input.rb:183:in `load_gemspec'
    /usr/lib/ruby/1.9.1/rubygems/package/tar_input.rb:51:in `block in initialize'
    /usr/lib/ruby/1.9.1/rubygems/package/tar_reader.rb:64:in `block in each'
    /usr/lib/ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `loop'
    /usr/lib/ruby/1.9.1/rubygems/package/tar_reader.rb:55:in `each'
    /usr/lib/ruby/1.9.1/rubygems/package/tar_input.rb:32:in `initialize'
    /usr/lib/ruby/1.9.1/rubygems/package/tar_input.rb:17:in `new'
    /usr/lib/ruby/1.9.1/rubygems/package/tar_input.rb:17:in `open'
    /usr/lib/ruby/1.9.1/rubygems/package.rb:58:in `open'
    /usr/lib/ruby/1.9.1/rubygems/format.rb:63:in `from_io'
    /usr/lib/ruby/1.9.1/rubygems/format.rb:51:in `block in from_file_by_path'
    /usr/lib/ruby/1.9.1/rubygems/format.rb:50:in `open'
    /usr/lib/ruby/1.9.1/rubygems/format.rb:50:in `from_file_by_path'
    /usr/lib/ruby/1.9.1/rubygems/installer.rb:118:in `initialize'
    /usr/lib/ruby/1.9.1/rubygems/dependency_installer.rb:264:in `new'
    /usr/lib/ruby/1.9.1/rubygems/dependency_installer.rb:264:in `block in install'
    /usr/lib/ruby/1.9.1/rubygems/dependency_installer.rb:247:in `each'
    /usr/lib/ruby/1.9.1/rubygems/dependency_installer.rb:247:in `install'
    /usr/lib/ruby/1.9.1/rubygems/commands/install_command.rb:119:in `block in execute'
    /usr/lib/ruby/1.9.1/rubygems/commands/install_command.rb:116:in `each'
    /usr/lib/ruby/1.9.1/rubygems/commands/install_command.rb:116:in `execute'
    /usr/lib/ruby/1.9.1/rubygems/command.rb:270:in `invoke'
    /usr/lib/ruby/1.9.1/rubygems/command_manager.rb:134:in `process_args'
    /usr/lib/ruby/1.9.1/rubygems/command_manager.rb:104:in `run'
    /usr/lib/ruby/1.9.1/rubygems/gem_runner.rb:58:in `run'
    /usr/bin/gem:21:in '<main>'
</pre>

I am running stock 1.9.2 on ubuntu 11.10 oneiric.

<pre>
ubuntu@machine:~$ ruby -v
ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]
ubuntu@machine:~$ gem -v
1.3.7
</pre>

I can install version 1.11.3, but not 1.11.3.1 or 1.11.3.2:

<pre>

ubuntu@machine:~$ sudo gem install rvm -v=1.11.3.1
ERROR:  While executing gem ... (ArgumentError)
    invalid byte sequence in US-ASCII
ubuntu@machine178:~$ sudo gem install rvm -v=1.11.3
***********************************************************************************
...
Successfully installed rvm-1.11.3
1 gem installed
Installing ri documentation for rvm-1.11.3...
Installing RDoc documentation for rvm-1.11.3...
</pre>

I am, however, able to install both of these troublesome versions without issue on my local machine that is running 1.9.3-p0 installed via rvm.

**Comment by mpapis** [comment]
please test with `rvm-1.11.3.3`

**Comment by fintanf** [comment]
That fixed it, thanks.
