### ISSUE TITLE
add rvmrc_create method

### ISSUE THREAD

**Issue by DanielKehoe** [rvm/rvm-gem#10]
I'm using the API in a Rails application template to set up an rvm gemset when an application is created with the `rails new -m` command. I appreciate being able to use the API method `RVM.gemset_create app_name`. I also want to create a `.rvmrc` file using the API. I can do this in my application template using Thor commands:

```
  create_file '.rvmrc' do
    "rvm #{rvm_env}"
  end
```

but I like the full-featured .rvmrc file I get when I use `$ rvm --rvmrc --create ruby-1.9.3-p194@myapp` in the shell.

I was expecting to be able to use an API method like `RVM.rvmrc_create "default@mygemset"` but after scanning the source code I don't see any methods to create an .rvmrc file in the API. Did I overlook it or is it missing? Would it make sense to add it?

**Comment by mpapis** [comment]
Closing as this will be provided as part of `RVM 2`.
