### ISSUE TITLE
Documentation URL is no longer good

### ISSUE THREAD

**Issue by wcooley** [rvm/rvm-gem#15]
The URL **https?://rvm.beginrescueend.com** is referred to in the in-line documentation and is the "Documentation" link on rubygems.org. The URL is also part of the Github description for this project. The "rvm" subdomain redirects to the parent, which is a blog in German, which is not the documentation that I expect.

**Comment by mpapis** [comment]
@wayneeseguin could you update the link in the description of the gem?
