### ISSUE TITLE
allow ruby switching

### ISSUE THREAD

**Issue by hbarrington** [rvm/rvm-gem#3]
allow switching of ruby versions

**Comment by ghost** [comment]
@mpapis inadvertent closure. This is for rvm-gem and NOT rvm. I read my Inbox too fast. I apologize.

I also deleted my previous response, it was inappropriate to rvm-gem.

**Comment by mpapis** [comment]
from #2:

> you can not change the loaded ruby version and you try to switch to 1.8.7 from 1.9.2 - this will not work, what you need is a possibility to select any ruby and allow running commands in context of this ruby, please open a new ticket for it

**Comment by hbarrington** [comment]
@mpapis thanks for the additional explanation. I was in a rush but wanted to get it up before leaving. Are there leads for how one might approach this problem?

**Comment by mpapis** [comment]
it requires changes in code, depending on the implementation it might require additional libraries. 

you could write some examples of what you need like:

```
RVM.with "1.9.3" do |e|
  e.run "echo $MY_RUBY_HOME"
end
```

also some details would be good:
- do you want to run `rvm` inside
- do you want to have `cd` handling inside for project files
- do you want to persist environment between two calls to `run`

@deryldoucette any more questions after experiences with rvm-test ?

**Comment by hbarrington** [comment]
persistent environment between two calls to run makes sense. I won't personally be needing `cd` but I could see others needing it. I'm not sure what you mean by running `rvm` inside... can you give an example?

the code block that you gave as an example would be great!

**Comment by hbarrington** [comment]
@mpapis let me know if you need more information

**Comment by mpapis** [comment]
I'm sorry for the delay, I'm on conference right now, will have a look into it starting from Monday.

**Comment by hbarrington** [comment]
@mpapis not at all! I appreciate the help and look forward to being able to use it. Thanks

**Comment by hbarrington** [comment]
@mpapis any luck? thanks again

**Comment by mpapis** [comment]
@hbarrington just got back from the conference, this feature has lower prio, it will take few days to find time for it (there is 15 other bugs waiting to be solved for RVM: https://github.com/wayneeseguin/rvm/issues?direction=desc&milestone=15&sort=created&state=open)

**Comment by hbarrington** [comment]
@mpapis completely understand. Thanks. I just needed to know where to spend my time coding and what the timeframe may or may not look like. It's greatly appreciated sir

**Comment by mpapis** [comment]
I have created it as a separate gem: https://github.com/mpapis/rvm-with
