### ISSUE TITLE
gemset_use! 

### ISSUE THREAD

**Issue by fdutey** [rvm/rvm-gem#5]
Hi.

Just to notice, there's always the bug with method 'gemset_use!' in lib/rvm/environment/gemset.rb:86

It just don't work with rails templates (result[:rvm_env_string] is nil).
I saw it was fixed in older version but it's still here

see here: https://github.com/wayneeseguin/rvm/issues/449
or here: https://github.com/wayneeseguin/rvm/pull/458

I manually fix the problem but now I need to build ruby configurations automatically (intent to migrate my co-workers from php to ruby) and I can't just fix it with scripts (path names depends on which ruby version is installed).

Thank you for your time.
Best regards.

**Comment by mpapis** [comment]
this change was reverted by @deryldoucette in https://github.com/wayneeseguin/rvm/commit/34e2cd0ef82c885b2b2054804f13e66283031a63 ... I have no idea which one is better, maybe there should by an or:

```
result[:GEM_HOME] || result[:rvm_env_string]
```

**Comment by lunks** [comment]
I'm using this on a rails template script and also have the same error.
